name: NodeJS Layer Integration Test
on:
  workflow_call:
    inputs:
      caller-workflow-name:
        required: true
        type: string
  workflow_dispatch:

concurrency:
  group: main-build-nodejs-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build-zip:
    runs-on: ubuntu-22.04
    name: nodejs-wrapper-${{ matrix.architecture }}
    strategy:
      fail-fast: false
      matrix:
        architecture: [ amd64, arm64 ]
        runtime: [nodejs18.x, nodejs20.x, nodejs22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: '~1.24.3'
          check-latest: true
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Cache (NodeJS)
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Patch ADOT
        run: ./patch-upstream.sh
     
      - name: Build layer Zip
        run: GOARCH=${{ matrix.architecture }} ./build.sh ${{ matrix.architecture }}
        working-directory: nodejs
      - name: find all zip hashFiles
        rub: find . -type f -name '*.zip'
      - name: Get Lambda Layer amd64 architecture value
        if: ${{ matrix.architecture == 'amd64' }}
        run: echo LAMBDA_FUNCTION_ARCH=x86_64 | tee --append $GITHUB_ENV
      - name: Get Lambda Layer arm64 architecture value
        if: ${{ matrix.architecture == 'arm64' }}
        run: echo LAMBDA_FUNCTION_ARCH=arm64 | tee --append $GITHUB_ENV
      - name: upload built ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-layer-${{matrix.runtime}}-${{matrix.architecture }}
          path: nodejs/layer/${{ matrix.architecture }}/*.zip
